# Overview {.unnumbered}

## Workshop schedule {.unnumbered}

```{r}
#| label: schedule
#| echo: false
#| message: false

library("tidyverse")

tribble(~`Time`, ~`Activity`,
        "09:15-09:30", "Introduction by workshop organizers",
        "09:30-10:00", "Lecture 1: eyetracking data pre-processing",
        "10:00-10:45", "Hands-on session 1",
        "10:45-11:00", "*BREAK*",
        "11:00-11:30", "Lecture 2: pre-processing (cont'd) and visualization",
        "11:30-12:15", "Hands-on session 2",
        "12:15-13:15", "*LUNCH* (provided)",
        "13:15-13:45", "Lecture 3: overview of statistical analysis",
        "13:45-14:15", "Hands-on session 3",
        "14:15-14:30", "*BREAK*",
        "14:30-15:00", "Lecture 4: cluster-based permutation analysis",
        "15:00-15:45", "Last hands-on session",
        "15:45-16:00", "Summary and discussion",
        "19:00", "*Dinner for Eyehub and workshop participants*") %>%
  knitr::kable()
```

## Getting prepared {.unnumbered}

We will be working through an existing dataset from a visual world eyetracking study, and writing code in R. You can also work with this dataset during the hands-on exercises, but feel free to try to apply these skills to your own data instead. 

Some experience with R and the tidyverse will be helpful, but the workshop will give you an overview of data analysis that will be useful even if you are not an R user, and even if you don't want to participate in the hands-on exercises. All of the materials from the workshop (code, data, slides) will be available at this site for later review.

For the participants wishing to participate in the hands-on parts, you will need the following:

- a laptop
- R version 4.0 or higher [(download from r-project.org)](https://cran.r-project.org/mirrors.html)
- an Integrated Development Environment such as the [RStudio IDE](https://www.rstudio.com/products/rstudio/download/) but feel free to use VSCode or emacs if you prefer and know how to make R scripts or RMarkdown documents in those
- the [tidyverse add-on package](https://www.tidyverse.org/) version 1.3 or higher
- add-on packages `lme4` and `remotes`

I won't be able to provide much tech support so it is a good idea to make sure everything is installed and working before Wednesday.

To find out what version of R you currently have, look at the message that appears when you start R, or type `R.version.string` in the R console. If you need help installing R and RStudio, please check [these resources kindly provided by the PsyTeachR team at the University of Glasgow](https://psyteachr.github.io/ads-v1/installing-r.html).

To find out what version of tidyverse you have, type `packageVersion("tidyverse")`. If you need to update tidyverse (i.e., if you have a version before 1.3), type `tidyverse::update_packages()` in the console and follow the instructions. You can also find more information about updating packages [at the psyteachr site](https://psyteachr.github.io/ads-v1/appendix-updating-r.html).

